/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package securityproject;

/**
 *
 * @author computer market
 */
public class design extends javax.swing.JFrame {

    SecurityProject spro;

    /**
     * Creates new form design
     */
    public design() {
        initComponents();
        this.setSize(1100, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100), new java.awt.Dimension(32767, 100));
        jLabel8 = new javax.swing.JLabel();
        privatet1A = new javax.swing.JLabel();
        ciphertextA = new javax.swing.JLabel();
        publict1 = new javax.swing.JLabel();
        privatet1 = new javax.swing.JLabel();
        ciphertext = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        p1 = new javax.swing.JTextField();
        q1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        m1 = new javax.swing.JTextField();
        e1 = new javax.swing.JTextField();
        encryption = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        publict1A = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        privatet2A = new javax.swing.JLabel();
        plaintextA = new javax.swing.JLabel();
        decryption = new javax.swing.JButton();
        e2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        p2 = new javax.swing.JTextField();
        plaintext = new javax.swing.JLabel();
        q2 = new javax.swing.JTextField();
        publict2 = new javax.swing.JLabel();
        m2 = new javax.swing.JTextField();
        privatet2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        publict2A = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("<RSA Algorithem>");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(288, 0, 197, 29);
        getContentPane().add(filler1);
        filler1.setBounds(675, 77, 0, 457);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Enter E:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 191, 63, 22);

        privatet1A.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        privatet1A.setText("Private key ");
        getContentPane().add(privatet1A);
        privatet1A.setBounds(237, 265, 64, 15);

        ciphertextA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ciphertextA.setText("Cipher Text ");
        getContentPane().add(ciphertextA);
        ciphertextA.setBounds(90, 451, 210, 17);

        publict1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        publict1.setText("Public key :");
        getContentPane().add(publict1);
        publict1.setBounds(162, 239, 62, 15);

        privatet1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        privatet1.setText("Private Key :");
        getContentPane().add(privatet1);
        privatet1.setBounds(162, 265, 69, 15);

        ciphertext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ciphertext.setText("Cipher Text :");
        getContentPane().add(ciphertext);
        ciphertext.setBounds(0, 451, 80, 17);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Generate Keys");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 231, 121, 49);
        getContentPane().add(p1);
        p1.setBounds(95, 77, 218, 37);
        getContentPane().add(q1);
        q1.setBounds(95, 125, 218, 37);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Enter P:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 92, 63, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Enter Q:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 140, 66, 22);
        getContentPane().add(m1);
        m1.setBounds(95, 286, 224, 35);
        getContentPane().add(e1);
        e1.setBounds(91, 180, 222, 33);

        encryption.setBackground(new java.awt.Color(255, 255, 255));
        encryption.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        encryption.setText("Encryption");
        encryption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptionActionPerformed(evt);
            }
        });
        getContentPane().add(encryption);
        encryption.setBounds(105, 362, 139, 49);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Massage");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 299, 67, 22);

        publict1A.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        publict1A.setText("Public key ");
        getContentPane().add(publict1A);
        publict1A.setBounds(234, 239, 58, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Enter E:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(371, 183, 63, 22);

        privatet2A.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        privatet2A.setText("Private key ");
        getContentPane().add(privatet2A);
        privatet2A.setBounds(601, 257, 64, 15);

        plaintextA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        plaintextA.setText("Plain Text");
        getContentPane().add(plaintextA);
        plaintextA.setBounds(437, 448, 250, 17);

        decryption.setBackground(new java.awt.Color(255, 255, 255));
        decryption.setFont(new java.awt.Font("Urdu Typesetting", 1, 24)); // NOI18N
        decryption.setText("Decryption");
        decryption.setAutoscrolls(true);
        decryption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptionActionPerformed(evt);
            }
        });
        getContentPane().add(decryption);
        decryption.setBounds(456, 363, 157, 41);

        e2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e2ActionPerformed(evt);
            }
        });
        getContentPane().add(e2);
        e2.setBounds(456, 174, 209, 31);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Generate Keys");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(372, 231, 121, 41);
        getContentPane().add(p2);
        p2.setBounds(455, 77, 210, 34);

        plaintext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        plaintext.setText("Plain Text :");
        getContentPane().add(plaintext);
        plaintext.setBounds(351, 448, 68, 17);

        q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2ActionPerformed(evt);
            }
        });
        getContentPane().add(q2);
        q2.setBounds(456, 122, 209, 34);

        publict2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        publict2.setText("Public key :");
        getContentPane().add(publict2);
        publict2.setBounds(511, 231, 62, 15);
        getContentPane().add(m2);
        m2.setBounds(456, 303, 209, 34);

        privatet2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        privatet2.setText("Private Key :");
        getContentPane().add(privatet2);
        privatet2.setBounds(511, 257, 69, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Enter P:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(371, 89, 63, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Enter Q:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(371, 134, 66, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Massage");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(371, 315, 67, 22);

        publict2A.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        publict2A.setText("Public key ");
        getContentPane().add(publict2A);
        publict2A.setBounds(598, 231, 58, 15);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(325, 35, 16, 510);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Reciever");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(514, 37, 91, 29);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Sender");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(95, 37, 74, 29);

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("Saeed Eldeeb");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(740, 20, 143, 29);

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setText("CS");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(800, 80, 37, 29);

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 204));
        jLabel13.setText("Section 2");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(770, 140, 110, 29);

        jLabel14.setBackground(new java.awt.Color(51, 0, 153));
        jLabel14.setForeground(new java.awt.Color(204, 0, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/securityproject/background.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(670, 0, 310, 540);

        jButton1.setText("send to reciver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 500, 110, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        spro = new SecurityProject(p1.getText(), q1.getText(), e1.getText());
        spro.check();
        publict1A.setText("(" + spro.Emath + "," + spro.nmath + ")");
        privatet1A.setText("(" + spro.dmath + "," + spro.nmath + ")");
        spro.getalphabet();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void encryptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptionActionPerformed
        spro = new SecurityProject(p2.getText(), q2.getText(), e2.getText());
        spro.check();
        spro.getMessageandEncrypt(m1.getText());
        ciphertextA.setText(spro.cipher.toString());
    }//GEN-LAST:event_encryptionActionPerformed

    private void decryptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptionActionPerformed
        spro = new SecurityProject(p2.getText(), q2.getText(), e2.getText());
        spro.check();
        spro.getMessageandDecrypt(m2.getText());
        plaintextA.setText(spro.cipher.toString());

    }//GEN-LAST:event_decryptionActionPerformed

    private void e2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        spro = new SecurityProject(p2.getText(), q2.getText(), e2.getText());
        spro.check();
        publict2A.setText("(" + spro.Emath + "," + spro.nmath + ")");
        privatet2A.setText("(" + spro.dmath + "," + spro.nmath + ")");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        m2.setText(ciphertextA.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new design().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ciphertext;
    private javax.swing.JLabel ciphertextA;
    private javax.swing.JButton decryption;
    private javax.swing.JTextField e1;
    private javax.swing.JTextField e2;
    private javax.swing.JButton encryption;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField m1;
    private javax.swing.JTextField m2;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JLabel plaintext;
    private javax.swing.JLabel plaintextA;
    private javax.swing.JLabel privatet1;
    private javax.swing.JLabel privatet1A;
    private javax.swing.JLabel privatet2;
    private javax.swing.JLabel privatet2A;
    private javax.swing.JLabel publict1;
    private javax.swing.JLabel publict1A;
    private javax.swing.JLabel publict2;
    private javax.swing.JLabel publict2A;
    private javax.swing.JTextField q1;
    private javax.swing.JTextField q2;
    // End of variables declaration//GEN-END:variables
}
